services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - PGTZ=Asia/Tokyo
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
  web:
    build: .
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: bash
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
