default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("RAILS_DB_USER") {"postgres"} %>
  password: <%= ENV.fetch("RAILS_DB_PASSWORD") {"password"} %>
  host: <%= ENV.fetch("RAILS_DB_HOST") {"localhost"} %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
